# .scrutinizer.yml
build:
    environment:
        php:
            version: 5.6.9
    project_setup:
        before:
            - mysql -e "CREATE DATABASE test"
    tests:
        override:
            -
                coverage:
                    file: 'build/logs/clover.xml'
                    format: 'php-clover'
